### ISSUE TITLE
Crash : IIllegalStateException: Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by adaonder** [kobakei/MaterialFabSpeedDial#33]
- OS: 8.1.0
- Device: Hytera PNC550
- Can reproduce on sample app: Yes

Library version: 1.2.1

FabSpeedDial.java line 491
io.github.kobakei.materialfabspeeddial.FabSpeedDial$6.run

LOG:: Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:799)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:299)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:281)
       at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
       at io.github.kobakei.materialfabspeeddial.FabSpeedDial$6.run(FabSpeedDial.java:491)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by jacobmattsson** [comment]
We experience this problem as well!
This seems to be the fix: https://stackoverflow.com/questions/26819429/cannot-start-this-animator-on-a-detached-view-reveal-effect
